"""
update_readme.py — write the results table into README.md from the results file.

The README's numbers are generated, never typed. This exists because the first
version of this project hand-maintained its results table and the table drifted
from the data: it printed a Phase-2 IoU next to a Phase-3 accuracy as one row,
carried a KMeans line that was a copy-paste of the Watershed line, and quoted an
inference time that appeared in no measurement file. A generated table cannot
drift, and `--check` makes a stale one a CI failure rather than a surprise.

    .venv/bin/python scripts/update_readme.py            # rewrite the block
    .venv/bin/python scripts/update_readme.py --check    # fail if stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from config import COUNT_TOLERANCE, METRICS_DIR, ROOT

BEGIN = "<!-- RESULTS:BEGIN -- generated by scripts/update_readme.py, do not edit -->"
END = "<!-- RESULTS:END -->"

ROWS = [
    ("watershed", "Watershed", "Classical"),
    ("kmeans", "KMeans (k=5)", "Classical"),
    ("yolo", "YOLOv8s-seg (fine-tuned)", "Deep learning"),
    ("hybrid", "Hybrid (density-aware)", "Hybrid"),
]


def render(data: dict) -> str:
    s, p = data["summary"], data["provenance"]

    best_iou = max(s[k]["mean_iou"] for k, _, _ in ROWS)
    best_acc = max(s[k]["count_accuracy_pct"] for k, _, _ in ROWS)
    best_mae = min(s[k]["mae"] for k, _, _ in ROWS)

    def cell(v, best, fmt):
        txt = fmt.format(v)
        return f"**{txt}**" if v == best else txt

    lines = [
        BEGIN,
        "",
        f"| Method | Type | Mean IoU | Count acc. (±{COUNT_TOLERANCE}) | MAE | Median latency |",
        "|---|---|---|---|---|---|",
    ]
    for key, name, typ in ROWS:
        m = s[key]
        lo, hi = m["iqr_inference_ms"]
        lines.append(
            f"| {name} | {typ} "
            f"| {cell(m['mean_iou'], best_iou, '{:.3f}')} "
            f"| {cell(m['count_accuracy_pct'], best_acc, '{:.0f}%')} "
            f"| {cell(m['mae'], best_mae, '{:.2f}')} "
            f"| {m['median_inference_ms']:.0f} ms "
            f"<sub>(IQR {lo:.0f}–{hi:.0f})</sub> |"
        )

    h = s["hybrid"]
    lines += [
        "",
        f"<sub>All four methods scored in a **single run** on the same "
        f"{p['n_test_images']} held-out test images, with the same metric "
        f"definitions, on the same device — `{p['device']}`, seed `{p['seed']}`, "
        f"{p['date']}. Instance IoU is class-agnostic under greedy one-to-one "
        f"matching; unmatched ground-truth objects score 0 and are included in "
        f"the mean. Latency is a median with an interquartile range, not a mean "
        f"over a cold start. torch {p['torch']}, ultralytics "
        f"{p['ultralytics']}, weights `{p['weights']}`.</sub>",
        "",
        f"<sub>The hybrid's density gate fired on **{h['dense_gate_fired']} of "
        f"{p['n_test_images']}** test images; the watershed cross-check then "
        f"altered the count on **{h['watershed_blend_applied']}** of them.</sub>",
        "",
        END,
    ]
    return "\n".join(lines)


def main() -> None:
    check = "--check" in sys.argv

    res_path = METRICS_DIR / "unified_results.json"
    if not res_path.exists():
        sys.exit(f"Missing {res_path}. Run src/evaluate.py first.")

    readme = ROOT / "README.md"
    text = readme.read_text()
    if BEGIN not in text or END not in text:
        sys.exit("README.md is missing the RESULTS markers.")

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = head + render(json.loads(res_path.read_text())) + tail

    if check:
        if updated != text:
            sys.exit("README results table is STALE — run without --check.")
        print("README results table is up to date.")
        return

    readme.write_text(updated)
    print(f"README results table regenerated from {res_path.name}")


if __name__ == "__main__":
    main()
